apiVersion: v1
kind: Service
metadata:
  name: user-buy-frontend-nodeport
spec:
  type: NodePort
  selector:
    app: user-buy-frontend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # Accessible on any cluster node at port 30080

