apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-buy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: user-buy.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-buy-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: customer-facing
            port:
              number: 80
