apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customer-facing-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: customer-facing
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customer-management-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: customer-management

